---
- hosts: default
  remote_user: vagrant
  sudo: true

  tasks:

  - name: update apt
    apt: update_cache=yes
         upgrade=yes
         cache_valid_time=3600

  - name: install apt packages
    apt: pkg={{ item }}
         state=installed
         cache_valid_time=3600
    with_items:
      - git
      - byobu
      - python-pip
      - python-virtualenv
      - python-numpy
      - python-sklearn

  - name: install pip packages
    pip: name={{ item }}
         state=latest
         virtualenv=/usr/local/virtualenv/sandbox-vm
    with_items:
      - ipython
      - https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl
